### ISSUE TITLE
Document how to achieve the screenshot in the README

### ISSUE THREAD

**Issue by ncalexan** [WJCFerguson/emacs-faff-theme#2]
First, I quite like this theme.  Thanks for publishing it!

I would like to know how to achieve the background and modeline in the screenshot.  I gather you're setting "ivory3" somewhere else; is there a reason that's not part of the theme definition?

Can you also document how you achieve the smoothly curved powerline left/right visuals?  Very nice.

Can you also suggest your font configuration?

**Comment by ncalexan** [comment]
> I would like to know how to achieve the background and modeline in the screenshot. I gather you're setting "ivory3" somewhere else; is there a reason that's not part of the theme definition?

A little more digging into my own configuration shows that my own `(custom-set-faces '(default ...))` is overriding the faff theme default, which is there.  Sorry for the noise!

**Comment by WJCFerguson** [comment]
Glad you like it, and worked out the default background.

The modeline is the `powerline` package that I have used  `customize` to configure with:

``` elisp
 '(powerline-default-separator (quote wave))
 '(powerline-display-buffer-size nil)
 '(powerline-height 20)
```

Font sizing... it's ugly.  I use Ubuntu, and the Ubuntu Mono font, but for some reason Emacs seems to render it in an ugly way unless I set the height to particular values.  So I have a `defun` that chooses from suitable values...  I use this for some automatic font size setting, between high DPI and older, moderate DPI displays.

``` elisp

(defvar ws-face-heights [90 102 117 132 147]
  "Array of face heights indexed by ws-font-height.")

;; =============================================================================
(defun ws-pixel-pitch ()
  "Calculate the pixel pitch for the current frame."
  (let ((monitor-attrs (frame-monitor-attributes)))
    (/ (float (nth 1 (assoc 'mm-size monitor-attrs)))
       (nth 3 (assoc 'geometry monitor-attrs)))))

;; =============================================================================
(defun ws-font-height (arg)
  "Return the index for ws-face-heights for the current frame.

Prefix ARG may be used to shift the index."
  (interactive "P")
  (elt ws-face-heights
       (min (- (length ws-face-heights) 1)
            (max 0
                 (+ 1
                    (if (numberp arg) arg 0)
                    (if (> (frame-pixel-width) 1920) 1 0)
                    (if (< (ws-pixel-pitch) 0.2) 2 0))))))

;; =============================================================================
(defun ws-fixfont (arg &optional frame)
  "Set the default font height appropriately for the window size.

Positive/negative prefix ARG selects size up/down.  FRAME selects
frame to act upon"
  (interactive "P")
  (when (display-graphic-p)
    (set-face-attribute 'default
                        (or frame (selected-frame))
                        :height (ws-font-height arg))))

```

Not sure if this helps, or just creates confusion.  There are almost certainly better ways...

**Comment by WJCFerguson** [comment]
Also using hl-line-mode, which is visible in the screenshot.  I'll try to augment the README some time soon.

**Comment by ncalexan** [comment]
> The modeline is the powerline package that I have used customize to configure with:

Beautiful, thanks!  I quite like the wave.

I did see the `hl-line` stuff -- you note it in the README, thank you for that -- but it's not to my taste.

**Comment by ncalexan** [comment]
> Not sure if this helps, or just creates confusion. There are almost certainly better ways...

This is very interesting, thank you!  I use Apple's Monaco, which if I recall was also height sensitive but I don't try to factor in the various monitor DPIs I use.  Many thanks for sharing.

**Comment by WJCFerguson** [comment]
Just tidying up - I think this can be closed now.
