### ISSUE TITLE
Unable to load color "ns_selection_color" using faff

### ISSUE THREAD

**Issue by ncalexan** [WJCFerguson/emacs-faff-theme#3]
I get the message
```
Unable to load color "ns_selection_color"
```
when I use faff.

It appears that `ns_selection_color` was split into two; see https://lists.gnu.org/archive/html/emacs-diffs/2013-09/msg00388.html.  Locally, replacing `ns_selection_color` with `ns_selection_bg_color` fixes things for me.  (I'm using `GNU Emacs 24.5.1 (x86_64-apple-darwin14.5.0, NS apple-appkit-1348.17) of 2016-02-02` on a Macbook Pro running El Capitan, 10.11.6.)

**Comment by ncalexan** [comment]
Oh!  Worth noting that this is note benign: the region is dark black without my fix.

**Comment by WJCFerguson** [comment]
Huh.  I originally created this from some auto theme generation - at least that use of ns-selection-color was not manually added by me.  Perhaps I can get rid of it.

**Comment by WJCFerguson** [comment]
Apologies, I forgot this existed.  It's removed now - by removing the region configuration entirely.  At least on my system I have no reason to deviate from the default, which appears to use the system default on Linux at least.
