### ISSUE TITLE
Invalid face box

### ISSUE THREAD

**Issue by dkislin** [WJCFerguson/emacs-faff-theme#4]
Hi! it's awesome theme especially for saving an eyes. Unfortunately, after the recent update from melpa I got the following error
`set-face-attribute: Invalid face box: :line-width, (1 . 1), :color, "grey75", :style, pressed-button`
and it looks like related to this [commit](https://github.com/WJCFerguson/emacs-faff-theme/commit/219f7a5f1dc648ffffd15fa8e2ee46c882e84367)
where, as i can see, the attribute box can't have property line-width be the cons (1 . 1) 
according to the documentation:
`﻿‘:box’
...
Otherwise,
VALUE must be a property list of the form ‘(:line-width WIDTH
:color COLOR :style STYLE)’.  If a keyword/value pair is missing from
the property list, a default value will be used for the value, as
specified below.  WIDTH specifies the width of the lines to draw; it
defaults to 1.  If WIDTH is negative, the absolute value is the width
of the lines, and draw top/bottom lines inside the characters area,
not around it.`

@WJCFerguson, Could you please take a look at this?, I haven't dive deeply in the faces customization myself ever

GNU Emacs 27.1 (build 1, x86_64-w64-mingw32) of 2020-08-21

**Comment by WJCFerguson** [comment]
Thanks for reporting this and apologies for creating the issue.  It seems to be a result of me tweaking the offending face in a recent build of the native-comp branch.  I've pushed a fix, tagged `2.15`, 37f396e.

**Comment by WJCFerguson** [comment]
Do let me know if you hit any incongruous looking faces or worse, or even if you just have opinions.
