### ISSUE TITLE
Invalid face box 

### ISSUE THREAD

**Issue by joanimato** [WJCFerguson/emacs-faff-theme#5]
After an update, I'm getting the following error on the theme:

`(error "Invalid face box" :line-width (2 . 1) :style released-button)`

Using emacs ver 27.2, on Mac-OS.

**Comment by WJCFerguson** [comment]
Apologies, I've done it again, I'll try to fix this asap.

**Comment by WJCFerguson** [comment]
Fixed.  Should ripple through soon.  Apologies for this, it's not the first time.  I'm running a build of recent Emacs `master` that allows this.

**Comment by WJCFerguson** [comment]
Fixed in 45f2faef92ee23738b86f4f8d0a433ad729a5ca8
